add_newline = false
command_timeout = 1000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$env_var\
$custom\
$line_break\
$jobs\
$status\
$character"""

[git_branch]
symbol = "\uf418 "
style = "purple"

[directory]
truncate_to_repo = false
truncation_length = 10

