add_newline = false
command_timeout = 1000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$env_var\
$custom\
$line_break\
$jobs\
$status\
$character"""

[git_branch]
symbol = "\uf418 "
style = "purple"

[git_status]
style = "red"
behind = "↓"
ahead = ""
diverged = "↕"

[directory]
truncate_to_repo = false
truncation_length = 10

# $git_status_simplified\
# [custom.git_status_simplified]
# when = 'test -n "$(git status --porcelain)"'
# symbol = '*'
# style = 'purple'
# format = '[$symbol$ahead_behind]($style)'
